# Project Log for Invsives SDM project

## Project Goal


## Ideas

This project started as building an SDM of Frangula alnus to use in a linked distribution and demographic model. 
However, based on feedback from reviewers on this manuscript (rejected from Biological Invasions in 4/2020), I've decided to separate the two sections of that MS and expand on the SDM version.

My goal is to model ca. 9 to 12 species, selecting from the LHPRISM Tier List. 
This project will focus on woody invasive species, and will include Frangula alnus.

Tier 1:

* *Nandina domestica*
* *Tamarix* ssp. (*T. chinensis, T. parviflora, T. ramosissima*)
* *Vitex rotundifolia*

Tier 2:

* *Actinidia arguta*
* *Alnus glutinosa*
* *Viburnum dilatatum*

Tier 3:

* *Aralia elata*
* *Pyrus calleryana*
* *Frangula alnus*

Tier 4:

* *Acer platanoides*
* *Ailanthus altissima*
* *Rhamnus cathartica*

## Thoughts on the analysis

* Probably going to use Maxent
* Follow Allen and Bradley 2016 as a model for doing the analysis for multiple species

## Thinks to think about futher

* How to deal with comparing native vs naturalized/invaded range?
    * Is MCP the best approach for getting background data in this case? 
    * Perhaps consider using the point-buffer approach?
* What is the spatial extent of my study?
    * At some point, I want to limit the projections to NY
    * Use "Eastern United States", so east of the Rockies? Similar to my F. alnus study?
